---

- hosts: all
  become: true
    
  tasks:
  - name: Define package names based on distro
    set_fact:
      apache_package: "{{ 'apache2' if ansible_distribution == 'Linux Mint' or ansible_os_family == 'Debian' else 'httpd' }}"
      php_package: "{{ 'libapache2-mod-php' if ansible_distribution == 'Linux Mint' or ansible_os_family == 'Debian' else 'php' }}"
  - name: Update cache and install apache and php packages
    package:
      name: 
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes
